language: python
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda env create -n GeCO --file conda-env.yml
- conda activate GeCO
script:
- black --check geco/
- coverage run -m pytest
after_success:
- codecov
deploy:
  provider: pypi
  username: __token__
  password:
    secure: OftUuY4kzZOZcTMn4lOFhNcj2KChFUvy/s2Q7/s4MCGiqn4Ig5jaBXFp6IMpQbN/uUoJCMXUyGcycfLzzUvI6JsX6f84lU21b67is7eIGwnlEYEkfBaNVCCsK+H62S5oZ2QIExB2kzNvzoTOPrhAnLaENfHAq+HEojxGGDuteJQ0uuXz3da6616TpKomLfkR4cO8Jj8+HsWW7UE3xk30JoiwoAd421UaQNl2dVtHIdrwhaHV3cFi7sUukBEPsNBbLymLyuXyvqi3Q5bLzaXrcAzEYEexl9p83hJ9TJs9C4UwMpw4TPYpR7KND6X/OcfzUOFp1x7hhreY5soVk1nE3ylpNzDVcRM7qgb0Ty7moLfSQu4wKKx6kKzErWWkeeitgMYSiGLsMPR4H/iNoWYK4X90XYz+ForzM2a8uBGaW5KpH/q7FxFsOLCF6XHO6ApmJIjgHGmh+5on/di893LvH4qobYPdqxW11O12phvXKO9eOuFCrcDpVqBIokDccDC/EMtatDbkCFM9k0Q58eriYrZQCcNU1Kj3f0AUrQLac5Bt7AT2f7cAB953yQEz/C2A+PPjPsl5YIclMbQeip0woOTapk0dBkC6XqgnFkOI7pjOcJLFhTGxKgaH9bk6R46xD+OGSiOsVvjg19ue1TAjGSHS/dRzELtHGOLJ0kRFm7M=
