# run: conda env create -n GeCO --file conda-env.yml
channels:
  - scipopt
  - conda-forge
  - default
dependencies:
  - python=3.8
  - pip
  - numpy
  - scipy
  - jupyter
  - pytest
  - pandas
  - tqdm
  - pyscipopt
  - networkx
  - pip:
      - git+https://github.com/rhgrant10/tsplib95.git
      - dwave_networkx
      - git+https://github.com/CharJon/GeCO
