package:
  name: geco
  version: 0.1.0

source:
  git_url: https://github.com/CharJon/GeCO

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - pyscipopt
    - networkx

about:
  summary: Generators for Combinatorial Optimization